include(ExternalProject)

SET(SDL2_RELEASE 2.30.0)
ExternalProject_Add(
	SDL2
	GIT_REPOSITORY "https://github.com/libsdl-org/SDL.git"
    GIT_TAG "release-${SDL2_RELEASE}"
    GIT_SHALLOW true
    UPDATE_COMMAND ""
    DOWNLOAD_DIR ${CMAKE_BINARY_DIR}
    SOURCE_DIR ${CMAKE_BINARY_DIR}/SDL2-${SDL2_RELEASE}
    BUILD_IN_SOURCE 0
    CMAKE_ARGS
        ${SDL_CMAKE_BUILD_OPTS}
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
        -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/${CMAKE_BUILD_TYPE}
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
)

MESSAGE(STATUS "SDL2 Installing to: ${CMAKE_INSTALL_PREFIX}/${CMAKE_BUILD_TYPE}")
SET(SDL2_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/${CMAKE_BUILD_TYPE}/include/SDL2)
SET(SDL2_LIBRARY_DIR ${CMAKE_INSTALL_PREFIX}/${CMAKE_BUILD_TYPE}/lib)
IF("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
    IF(WIN32)
        set(SDL2_LIBRARIES "SDL2maind.lib;SDL2d.lib")
        set(SDL2_LIBRARY "SDL2d.lib")
    ELSE()
        set(SDL2_LIBRARIES "SDL2maind;SDL2-2.0d")
        set(SDL2_LIBRARY "SDL2-2.0d")
    ENDIF()
ELSE()
    IF(WIN32)
        set(SDL2_LIBRARIES "SDL2main.lib;SDL2.lib")
        set(SDL2_LIBRARY "SDL2.lib")
    ELSE()
        set(SDL2_LIBRARIES "SDL2main;SDL2-2.0")
        set(SDL2_LIBRARY "SDL2-2.0")
    ENDIF()
ENDIF()

SET(SDL2_TTF_RELEASE 2.22.0)
ExternalProject_Add(
    SDL2_ttf
    GIT_REPOSITORY "https://github.com/libsdl-org/SDL_ttf.git"
    GIT_TAG "release-${SDL2_TTF_RELEASE}"
    GIT_SHALLOW true
    UPDATE_COMMAND ""
    DOWNLOAD_DIR ${CMAKE_BINARY_DIR}
    SOURCE_DIR ${CMAKE_BINARY_DIR}/sdl2_ttf
    BUILD_IN_SOURCE 0
    CMAKE_ARGS
    ${SDL2_TTF_CMAKE_BUILD_OPTS}
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
        -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/${CMAKE_BUILD_TYPE}
        -DCMAKE_C_FLAGS=${EXTERNAL_C_FLAGS}
        -DSDL2_INCLUDE_DIR=${SDL2_INCLUDE_DIR}
)

ADD_DEPENDENCIES(SDL2_ttf SDL2)
MESSAGE(STATUS "SDL2_ttf Installing to: ${CMAKE_INSTALL_PREFIX}/${CMAKE_BUILD_TYPE}")
SET(SDL2_TTF_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/${CMAKE_BUILD_TYPE}/include/SDL2_ttf)
SET(SDL2_TTF_LIBRARY_DIR ${CMAKE_INSTALL_PREFIX}/${CMAKE_BUILD_TYPE}/lib)
IF("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
    IF(WIN32)
        set(SDL2_TTF_LIBRARY "SDL2_ttfd.lib")
    ELSE()
        set(SDL2_TTF_LIBRARY "SDL2_ttf")
    ENDIF()
ELSE()
    IF(WIN32)
        set(SDL2_TTF_LIBRARY "SDL2_ttf.lib")
    ELSE()
        set(SDL2_TTF_LIBRARY "SDL2_ttf")
    ENDIF()
ENDIF()

SET(NFD_RELEASE 1.1.1)
ExternalProject_Add(
	NFD
	GIT_REPOSITORY "https://github.com/btzy/nativefiledialog-extended.git"
    GIT_TAG "v${NFD_RELEASE}"
    GIT_SHALLOW true
    UPDATE_COMMAND ""
    DOWNLOAD_DIR ${CMAKE_BINARY_DIR}
    SOURCE_DIR ${CMAKE_BINARY_DIR}/NFD-${NFD_RELEASE}
    BUILD_IN_SOURCE 0
    CMAKE_ARGS
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
        -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/${CMAKE_BUILD_TYPE}
)

MESSAGE(STATUS "NFD Installing to: ${CMAKE_INSTALL_PREFIX}/${CMAKE_BUILD_TYPE}")
SET(NFD_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/${CMAKE_BUILD_TYPE}/include)
SET(NFD_LIBRARY_DIR ${CMAKE_INSTALL_PREFIX}/${CMAKE_BUILD_TYPE}/lib)
IF("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
    IF(WIN32)
        set(NFD_LIBRARY "nfd.lib")
    ELSE()
        set(NFD_LIBRARY "nfd")
    ENDIF()
ELSE()
    IF(WIN32)
        set(NFD_LIBRARY "nfd.lib")
    ELSE()
        set(NFD_LIBRARY "nfd")
    ENDIF()
ENDIF()