name: Test ROMs
on:
  workflow_dispatch:

jobs:
  build-and-run-test-roms:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: CMake Configure (Release)
        run: cmake -B ./platform/sdl/build ./platform/sdl -DCMAKE_BUILD_TYPE=Release
      
      - name: Build with Make (Release)
        working-directory: ./platform/sdl/build
        run: make

      - name: Download and Extract Test ROMs
        run: |
          curl -L https://github.com/c-sp/gameboy-test-roms/releases/download/v7.0/game-boy-test-roms-v7.0.zip -o test-roms.zip
          unzip test-roms.zip -d ./platform/sdl/build/test-roms

      - name: Run Knowboy with Test ROM
        working-directory: ./platform/sdl/build
        run: |
          timeout 60 bash -c \
          '{
            stdbuf -oL -eL ./Knowboy --bootrom none --gamerom ./test-roms/blargg/cpu_instrs/cpu_instrs.gb --start --noninteractive > output.log & pid=$!
            while ! awk -F'DEBUG SER: ' '{if(NF>1) printf "%s", $2}' output.log | grep -q "Passed all tests"; do
              sleep 1
              if ! kill -0 $pid 2>/dev/null; then
                echo "Knowboy process ended unexpectedly."
                exit 1
              fi
            done
            echo "Passed all CPU tests"
            kill $pid && exit 0
            } || { echo "Test output not detected within timeout period."; exit 1; }'